version: '3.9'
services:
  apache:
    image: httpd:latest
    container_name: myapache
    ports:
    - '80:80'
    - '443:443'
    volumes:
    - ./website:/usr/local/apache2/htdocs
    - ./conf:/usr/local/apache2/conf/
